# Generated by Django 5.0 on 2023-12-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBook',
            fields=[
                ('request_book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_date', models.CharField(max_length=100)),
                ('request_date', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
