# Generated by Django 5.0 on 2023-12-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('borrowbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('return_book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('returnDate', models.DateField()),
                ('condition', models.CharField(max_length=20)),
                ('isOverdue', models.BooleanField(default=False)),
                ('borrow_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowbook.borrowbook')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
