# Generated by Django 5.0 on 2023-12-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returnbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='condition',
        ),
    ]
