# Generated by Django 5.0 on 2023-12-15 12:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationBook',
            fields=[
                ('donation_book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('donation_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField(default=1)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
